#!/bin/bash
name=hw.js
jq "(.home[]|select(.title==\"$1\")|.content)|=\"$2\"" $name  > $name.new1
jq "(.home[]|select(.title==\"$1\")|.date)|=\"$3\"" $name.new1  > $name.new2
rm $name.new1
mv $name{.new2,}
